language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build
  - ./gradlew test

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "akshatsrivastava13"
  - git config --local user.email "akshat.mukesh@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-Supra-${TRAVIS_BUILD_NUMBER}}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  file: app/build/outputs/apk/release/app-release.apk
  overwrite: true
  skip_cleanup: true
  api_key: $GH_TOKEN
  on:
    branch: master